name: Test rules

on:
  push:
  pull_request:

jobs:
  ast-grep-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install -g --trust @ast-grep/cli
      - run: ast-grep test --config sgconfig.yml
